# Generated by Django 4.0.6 on 2022-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstname',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastname',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='members',
            name='Year',
            field=models.CharField(default=1900, max_length=255),
            preserve_default=False,
        ),
    ]
